services:
  stark.admin:
    image: stark.admin
    build:
      context: .
      dockerfile: service/Stark.Admin/Dockerfile
    volumes:
      - /home/data/stark/wiki:/app/wiki #配置数据库磁盘挂载
      - /home/data/stark/stark.db:/app/stark.db #配置数据库磁盘挂载
    ports:
      - '8881:80'